-- =====================================================================
-- GLOBAL SALES & CUSTOMER TIERING ANALYTICS PIPELINE
-- Architecture: Medallion Pattern (Bronze -> Silver -> Gold) in Snowflake
-- =====================================================================

-- 1. ADMINISTRATIVE ROLE AND WAREHOUSE CONFIGURATION

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE WH_GLOBAL_SALES_PRO
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

-- 2. DATABASE AND MEDALLION ARCHITECTURE SCHEMAS

CREATE OR REPLACE DATABASE GLOBAL_SALES_DB;

CREATE OR REPLACE SCHEMA GLOBAL_SALES_DB.BRONZE;
CREATE OR REPLACE SCHEMA GLOBAL_SALES_DB.SILVER;
CREATE OR REPLACE SCHEMA GLOBAL_SALES_DB.GOLD;
CREATE OR REPLACE SCHEMA GLOBAL_SALES_DB.UTILITIES;


-- =====================================================================
-- 3. EXTERNAL STAGE & RAW INGESTION (BRONZE LAYER)
-- =====================================================================

-- Storage Integration with Cloud Storage (GCS/S3)

CREATE OR REPLACE STORAGE INTEGRATION SI_GLOBAL_SALES
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = GCS
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('gcs://global-sales-bucket-prod/raw_transactions/');

-- File Format Definition for Semi-Structured / CSV Sales Data

CREATE OR REPLACE FILE FORMAT GLOBAL_SALES_DB.BRONZE.FF_SALES_CSV
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    FIELD_DELIMITER = ','
    NULL_IF = ('NULL', 'N/A', '');

-- External Stage Setup

CREATE OR REPLACE STAGE GLOBAL_SALES_DB.BRONZE.STG_GLOBAL_SALES
    URL = 'gcs://global-sales-bucket-prod/raw_transactions/'
    STORAGE_INTEGRATION = SI_GLOBAL_SALES
    FILE_FORMAT = GLOBAL_SALES_DB.BRONZE.FF_SALES_CSV;

-- Raw Table Creation (All fields as STRING for safe landing)

CREATE OR REPLACE TABLE GLOBAL_SALES_DB.BRONZE.RAW_TRANSACTIONS (
    "TRANSACTION_ID" STRING,
    "ORDER_DATE" STRING,
    "CUSTOMER_ID" STRING,
    "STORE_COUNTRY" STRING,
    "PRODUCT_CATEGORY" STRING,
    "QUANTITY" STRING,
    "UNIT_PRICE" STRING,
    "CURRENCY" STRING
);

-- Bulk Ingestion with Pattern Matching and Error Handling

COPY INTO GLOBAL_SALES_DB.BRONZE.RAW_TRANSACTIONS
FROM @GLOBAL_SALES_DB.BRONZE.STG_GLOBAL_SALES
FILE_FORMAT = (FORMAT_NAME = GLOBAL_SALES_DB.BRONZE.FF_SALES_CSV)
PATTERN = '.*_sales_2026\.csv'
ON_ERROR = 'CONTINUE';


-- =====================================================================
-- 4. REUSABLE SQL CUSTOM FUNCTION (UTILITIES SCHEMA)
-- =====================================================================

-- Function to determine the Fiscal Quarter based on transaction date

CREATE OR REPLACE FUNCTION GLOBAL_SALES_DB.UTILITIES.GET_FISCAL_QUARTER(ORDER_DATE DATE)
RETURNS STRING
AS
$$
    CASE 
        WHEN MONTH(ORDER_DATE) IN (1, 2, 3) THEN 'Q1-FY'
        WHEN MONTH(ORDER_DATE) IN (4, 5, 6) THEN 'Q2-FY'
        WHEN MONTH(ORDER_DATE) IN (7, 8, 9) THEN 'Q3-FY'
        WHEN MONTH(ORDER_DATE) IN (10, 11, 12) THEN 'Q4-FY'
        ELSE 'UNKNOWN'
    END
$$;


-- =====================================================================
-- 5. DATA CLEANSING, CASTING & BUSINESS RULES (SILVER LAYER)
-- =====================================================================

CREATE OR REPLACE TABLE GLOBAL_SALES_DB.SILVER.SILVER_TRANSACTIONS (
    TRANSACTION_ID INT,
    ORDER_DATE DATE,
    FISCAL_QUARTER STRING,
    CUSTOMER_ID INT,
    STORE_COUNTRY STRING,
    PRODUCT_CATEGORY STRING,
    QUANTITY INT,
    UNIT_PRICE DECIMAL(15,2),
    GROSS_REVENUE DECIMAL(15,2),
    NET_REVENUE DECIMAL(15,2),
    CURRENCY STRING
);

INSERT INTO GLOBAL_SALES_DB.SILVER.SILVER_TRANSACTIONS
SELECT
    TRY_CAST("TRANSACTION_ID" AS INT),
    TO_DATE("ORDER_DATE", 'YYYY-MM-DD'),
    GLOBAL_SALES_DB.UTILITIES.GET_FISCAL_QUARTER(TO_DATE("ORDER_DATE", 'YYYY-MM-DD')),
    TRY_CAST("CUSTOMER_ID" AS INT),
    "STORE_COUNTRY",
    "PRODUCT_CATEGORY",
    TRY_CAST("QUANTITY" AS INT),
    TRY_CAST("UNIT_PRICE" AS DECIMAL(15,2)),
    (TRY_CAST("QUANTITY" AS INT) * TRY_CAST("UNIT_PRICE" AS DECIMAL(15,2))) AS GROSS_REVENUE,
    -- Applying a regional corporate tax / net adjustment factor of 92%
    ROUND((TRY_CAST("QUANTITY" AS INT) * TRY_CAST("UNIT_PRICE" AS DECIMAL(15,2))) * 0.92, 2) AS NET_REVENUE,
    "CURRENCY"
FROM GLOBAL_SALES_DB.BRONZE.RAW_TRANSACTIONS
WHERE "TRANSACTION_ID" IS NOT NULL;


-- =====================================================================
-- 6. ADVANCED ANALYTICS & WINDOW FUNCTIONS (GOLD LAYER)
-- =====================================================================

CREATE OR REPLACE TABLE GLOBAL_SALES_DB.GOLD.GOLD_CUSTOMER_SALES_SUMMARY AS 
WITH CustomerAggregates AS (
    SELECT
        CUSTOMER_ID,
        STORE_COUNTRY,
        COUNT(DISTINCT TRANSACTION_ID) AS TOTAL_ORDERS,
        SUM(NET_REVENUE) AS LIFETIME_SPEND,
        MAX(ORDER_DATE) AS LAST_PURCHASE_DATE
    FROM GLOBAL_SALES_DB.SILVER.SILVER_TRANSACTIONS
    GROUP BY CUSTOMER_ID, STORE_COUNTRY
),
CustomerRanking AS (
    SELECT
        CUSTOMER_ID,
        STORE_COUNTRY,
        TOTAL_ORDERS,
        LIFETIME_SPEND,
        LAST_PURCHASE_DATE,
        PERCENT_RANK() OVER (PARTITION BY STORE_COUNTRY ORDER BY LIFETIME_SPEND DESC) as SPEND_PERCENTILE
    FROM CustomerAggregates
)
SELECT
    CUSTOMER_ID,
    STORE_COUNTRY,
    TOTAL_ORDERS,
    LIFETIME_SPEND,
    LAST_PURCHASE_DATE,
    CASE 
        WHEN SPEND_PERCENTILE <= 0.10 THEN 'VIP Platinum'
        WHEN SPEND_PERCENTILE <= 0.30 THEN 'Gold Tier'
        WHEN SPEND_PERCENTILE <= 0.60 THEN 'Silver Tier'
        ELSE 'Standard'
    END AS CUSTOMER_SEGMENT
FROM CustomerRanking
ORDER BY STORE_COUNTRY, LIFETIME_SPEND DESC;

-- Final Verification Query for Business Stakeholders / BI Tools

SELECT * FROM GLOBAL_SALES_DB.GOLD.GOLD_CUSTOMER_SALES_SUMMARY;